/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as ApiQuotaRouteImport } from './routes/api/quota'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated/chat.$conversationId'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'
import { Route as ApiAccountExportRouteImport } from './routes/api/account/export'
import { Route as ApiDeviceLinkTokenRouteImport } from './routes/api/device-link/token'
import { Route as ApiMediaPhotosRouteImport } from './routes/api/media/photos'
import { Route as ApiMediaVoiceRouteImport } from './routes/api/media/voice'
import { Route as ApiPreferencesChatRouteImport } from './routes/api/preferences/chat'
import { Route as ApiPublicDeviceLinkRedeemRouteImport } from './routes/api/public/device-link/redeem'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiChatConversationsConversationIdBackfillRouteImport } from './routes/api/chat/conversations.$conversationId.backfill'
import { Route as ApiChatMessagesMessageIdTranslateRouteImport } from './routes/api/chat/messages.$messageId.translate'
import { Route as ApiChatMessagesMessageIdTranslationRouteImport } from './routes/api/chat/messages.$messageId.translation'
import { Route as ApiMediaVoiceMessageIdTranscribeRouteImport } from './routes/api/media/voice.$messageId.transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiQuotaRoute = ApiQuotaRouteImport.update({
  id: '/api/quota',
  path: '/api/quota',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/chat/$conversationId',
    path: '/chat/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountExportRoute = ApiAccountExportRouteImport.update({
  id: '/api/account/export',
  path: '/api/account/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceLinkTokenRoute = ApiDeviceLinkTokenRouteImport.update({
  id: '/api/device-link/token',
  path: '/api/device-link/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaPhotosRoute = ApiMediaPhotosRouteImport.update({
  id: '/api/media/photos',
  path: '/api/media/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaVoiceRoute = ApiMediaVoiceRouteImport.update({
  id: '/api/media/voice',
  path: '/api/media/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreferencesChatRoute = ApiPreferencesChatRouteImport.update({
  id: '/api/preferences/chat',
  path: '/api/preferences/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceLinkRedeemRoute =
  ApiPublicDeviceLinkRedeemRouteImport.update({
    id: '/api/public/device-link/redeem',
    path: '/api/public/device-link/redeem',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatConversationsConversationIdBackfillRoute =
  ApiChatConversationsConversationIdBackfillRouteImport.update({
    id: '/api/chat/conversations/$conversationId/backfill',
    path: '/api/chat/conversations/$conversationId/backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatMessagesMessageIdTranslateRoute =
  ApiChatMessagesMessageIdTranslateRouteImport.update({
    id: '/api/chat/messages/$messageId/translate',
    path: '/api/chat/messages/$messageId/translate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatMessagesMessageIdTranslationRoute =
  ApiChatMessagesMessageIdTranslationRouteImport.update({
    id: '/api/chat/messages/$messageId/translation',
    path: '/api/chat/messages/$messageId/translation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMediaVoiceMessageIdTranscribeRoute =
  ApiMediaVoiceMessageIdTranscribeRouteImport.update({
    id: '/$messageId/transcribe',
    path: '/$messageId/transcribe',
    getParentRoute: () => ApiMediaVoiceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/api/quota': typeof ApiQuotaRoute
  '/join/$code': typeof JoinCodeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/device-link/token': typeof ApiDeviceLinkTokenRoute
  '/api/media/photos': typeof ApiMediaPhotosRoute
  '/api/media/voice': typeof ApiMediaVoiceRouteWithChildren
  '/api/preferences/chat': typeof ApiPreferencesChatRoute
  '/api/public/device-link/redeem': typeof ApiPublicDeviceLinkRedeemRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/chat/conversations/$conversationId/backfill': typeof ApiChatConversationsConversationIdBackfillRoute
  '/api/chat/messages/$messageId/translate': typeof ApiChatMessagesMessageIdTranslateRoute
  '/api/chat/messages/$messageId/translation': typeof ApiChatMessagesMessageIdTranslationRoute
  '/api/media/voice/$messageId/transcribe': typeof ApiMediaVoiceMessageIdTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/api/quota': typeof ApiQuotaRoute
  '/join/$code': typeof JoinCodeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/device-link/token': typeof ApiDeviceLinkTokenRoute
  '/api/media/photos': typeof ApiMediaPhotosRoute
  '/api/media/voice': typeof ApiMediaVoiceRouteWithChildren
  '/api/preferences/chat': typeof ApiPreferencesChatRoute
  '/api/public/device-link/redeem': typeof ApiPublicDeviceLinkRedeemRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/chat/conversations/$conversationId/backfill': typeof ApiChatConversationsConversationIdBackfillRoute
  '/api/chat/messages/$messageId/translate': typeof ApiChatMessagesMessageIdTranslateRoute
  '/api/chat/messages/$messageId/translation': typeof ApiChatMessagesMessageIdTranslationRoute
  '/api/media/voice/$messageId/transcribe': typeof ApiMediaVoiceMessageIdTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/api/quota': typeof ApiQuotaRoute
  '/join/$code': typeof JoinCodeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/device-link/token': typeof ApiDeviceLinkTokenRoute
  '/api/media/photos': typeof ApiMediaPhotosRoute
  '/api/media/voice': typeof ApiMediaVoiceRouteWithChildren
  '/api/preferences/chat': typeof ApiPreferencesChatRoute
  '/api/public/device-link/redeem': typeof ApiPublicDeviceLinkRedeemRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/chat/conversations/$conversationId/backfill': typeof ApiChatConversationsConversationIdBackfillRoute
  '/api/chat/messages/$messageId/translate': typeof ApiChatMessagesMessageIdTranslateRoute
  '/api/chat/messages/$messageId/translation': typeof ApiChatMessagesMessageIdTranslationRoute
  '/api/media/voice/$messageId/transcribe': typeof ApiMediaVoiceMessageIdTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/chats'
    | '/friends'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/api/quota'
    | '/join/$code'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/chat/$conversationId'
    | '/api/account/delete'
    | '/api/account/export'
    | '/api/device-link/token'
    | '/api/media/photos'
    | '/api/media/voice'
    | '/api/preferences/chat'
    | '/api/public/device-link/redeem'
    | '/api/public/payments/webhook'
    | '/api/chat/conversations/$conversationId/backfill'
    | '/api/chat/messages/$messageId/translate'
    | '/api/chat/messages/$messageId/translation'
    | '/api/media/voice/$messageId/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/chats'
    | '/friends'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/api/quota'
    | '/join/$code'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/chat/$conversationId'
    | '/api/account/delete'
    | '/api/account/export'
    | '/api/device-link/token'
    | '/api/media/photos'
    | '/api/media/voice'
    | '/api/preferences/chat'
    | '/api/public/device-link/redeem'
    | '/api/public/payments/webhook'
    | '/api/chat/conversations/$conversationId/backfill'
    | '/api/chat/messages/$messageId/translate'
    | '/api/chat/messages/$messageId/translation'
    | '/api/media/voice/$messageId/transcribe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/chats'
    | '/_authenticated/friends'
    | '/_authenticated/onboarding'
    | '/_authenticated/premium'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/api/quota'
    | '/join/$code'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/chat/$conversationId'
    | '/api/account/delete'
    | '/api/account/export'
    | '/api/device-link/token'
    | '/api/media/photos'
    | '/api/media/voice'
    | '/api/preferences/chat'
    | '/api/public/device-link/redeem'
    | '/api/public/payments/webhook'
    | '/api/chat/conversations/$conversationId/backfill'
    | '/api/chat/messages/$messageId/translate'
    | '/api/chat/messages/$messageId/translation'
    | '/api/media/voice/$messageId/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiQuotaRoute: typeof ApiQuotaRoute
  JoinCodeRoute: typeof JoinCodeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAccountExportRoute: typeof ApiAccountExportRoute
  ApiDeviceLinkTokenRoute: typeof ApiDeviceLinkTokenRoute
  ApiMediaPhotosRoute: typeof ApiMediaPhotosRoute
  ApiMediaVoiceRoute: typeof ApiMediaVoiceRouteWithChildren
  ApiPreferencesChatRoute: typeof ApiPreferencesChatRoute
  ApiPublicDeviceLinkRedeemRoute: typeof ApiPublicDeviceLinkRedeemRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiChatConversationsConversationIdBackfillRoute: typeof ApiChatConversationsConversationIdBackfillRoute
  ApiChatMessagesMessageIdTranslateRoute: typeof ApiChatMessagesMessageIdTranslateRoute
  ApiChatMessagesMessageIdTranslationRoute: typeof ApiChatMessagesMessageIdTranslationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/quota': {
      id: '/api/quota'
      path: '/api/quota'
      fullPath: '/api/quota'
      preLoaderRoute: typeof ApiQuotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/export': {
      id: '/api/account/export'
      path: '/api/account/export'
      fullPath: '/api/account/export'
      preLoaderRoute: typeof ApiAccountExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device-link/token': {
      id: '/api/device-link/token'
      path: '/api/device-link/token'
      fullPath: '/api/device-link/token'
      preLoaderRoute: typeof ApiDeviceLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/photos': {
      id: '/api/media/photos'
      path: '/api/media/photos'
      fullPath: '/api/media/photos'
      preLoaderRoute: typeof ApiMediaPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/voice': {
      id: '/api/media/voice'
      path: '/api/media/voice'
      fullPath: '/api/media/voice'
      preLoaderRoute: typeof ApiMediaVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preferences/chat': {
      id: '/api/preferences/chat'
      path: '/api/preferences/chat'
      fullPath: '/api/preferences/chat'
      preLoaderRoute: typeof ApiPreferencesChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device-link/redeem': {
      id: '/api/public/device-link/redeem'
      path: '/api/public/device-link/redeem'
      fullPath: '/api/public/device-link/redeem'
      preLoaderRoute: typeof ApiPublicDeviceLinkRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/conversations/$conversationId/backfill': {
      id: '/api/chat/conversations/$conversationId/backfill'
      path: '/api/chat/conversations/$conversationId/backfill'
      fullPath: '/api/chat/conversations/$conversationId/backfill'
      preLoaderRoute: typeof ApiChatConversationsConversationIdBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/messages/$messageId/translate': {
      id: '/api/chat/messages/$messageId/translate'
      path: '/api/chat/messages/$messageId/translate'
      fullPath: '/api/chat/messages/$messageId/translate'
      preLoaderRoute: typeof ApiChatMessagesMessageIdTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/messages/$messageId/translation': {
      id: '/api/chat/messages/$messageId/translation'
      path: '/api/chat/messages/$messageId/translation'
      fullPath: '/api/chat/messages/$messageId/translation'
      preLoaderRoute: typeof ApiChatMessagesMessageIdTranslationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/voice/$messageId/transcribe': {
      id: '/api/media/voice/$messageId/transcribe'
      path: '/$messageId/transcribe'
      fullPath: '/api/media/voice/$messageId/transcribe'
      preLoaderRoute: typeof ApiMediaVoiceMessageIdTranscribeRouteImport
      parentRoute: typeof ApiMediaVoiceRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiMediaVoiceRouteChildren {
  ApiMediaVoiceMessageIdTranscribeRoute: typeof ApiMediaVoiceMessageIdTranscribeRoute
}

const ApiMediaVoiceRouteChildren: ApiMediaVoiceRouteChildren = {
  ApiMediaVoiceMessageIdTranscribeRoute: ApiMediaVoiceMessageIdTranscribeRoute,
}

const ApiMediaVoiceRouteWithChildren = ApiMediaVoiceRoute._addFileChildren(
  ApiMediaVoiceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiQuotaRoute: ApiQuotaRoute,
  JoinCodeRoute: JoinCodeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAccountExportRoute: ApiAccountExportRoute,
  ApiDeviceLinkTokenRoute: ApiDeviceLinkTokenRoute,
  ApiMediaPhotosRoute: ApiMediaPhotosRoute,
  ApiMediaVoiceRoute: ApiMediaVoiceRouteWithChildren,
  ApiPreferencesChatRoute: ApiPreferencesChatRoute,
  ApiPublicDeviceLinkRedeemRoute: ApiPublicDeviceLinkRedeemRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiChatConversationsConversationIdBackfillRoute:
    ApiChatConversationsConversationIdBackfillRoute,
  ApiChatMessagesMessageIdTranslateRoute:
    ApiChatMessagesMessageIdTranslateRoute,
  ApiChatMessagesMessageIdTranslationRoute:
    ApiChatMessagesMessageIdTranslationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
